let lastRows=[];
const $=id=>document.getElementById(id);
function parseCSV(text){const lines=text.trim().split(/\r?\n/);const h=lines.shift().split(',');return lines.map(line=>{const v=line.split(',');const o={};h.forEach((k,i)=>o[k]=v[i]??'');return o})}
function rank(vals,positive=false){let arr=vals.map((v,i)=>({v:+v||0,i}));let eligible=positive?arr.filter(x=>x.v>0):arr;eligible.sort((a,b)=>a.v-b.v);let out=Array(vals.length).fill(0);if(!eligible.length)return out;let i=0;while(i<eligible.length){let j=i;while(j+1<eligible.length&&eligible[j+1].v===eligible[i].v)j++;let avg=((i+1)+(j+1))/2/eligible.length;for(let k=i;k<=j;k++)out[eligible[k].i]=avg;i=j+1}return out}
function score(rows){const rel=rows.map(r=>Math.max(0,-(+r.adjusted_change_pct||0)/100));const annual=rows.map(r=>Math.max(0,+r.annualized_kwh_saved||0));const area=rows.map(r=>Math.max(0,+r.gross_floor_area||0));const reach=rows.map((r,i)=>(+r.capacity||0)>0?(+r.capacity):Math.sqrt(area[i]));const E=rank(rel,true),V=rank(annual,true),S=rank(reach,true),scale=rank(area.map(x=>Math.log1p(x))),vol=rank(rows.map(r=>+r.pre_cv||0));let out=rows.map((r,i)=>{let svg=(E[i]>0&&V[i]>0&&S[i]>0)?Math.cbrt(E[i]*V[i]*S[i]):0;let type=r.event_type==='LED_Installation'?.30:r.event_type==='HVAC_Tuning'?.55:.50;let ic=.40*type+.35*scale[i]+.25*vol[i];return {...r,shared_value_gain:svg,implementation_complexity:ic}});out.forEach((r,i)=>{r.frontier=!out.some((q,j)=>j!==i&&q.implementation_complexity<=r.implementation_complexity&&q.shared_value_gain>=r.shared_value_gain&&(q.implementation_complexity<r.implementation_complexity||q.shared_value_gain>r.shared_value_gain))});return out}
function render(rows,label){lastRows=score(rows);const f=lastRows.filter(r=>r.frontier).sort((a,b)=>a.implementation_complexity-b.implementation_complexity);$('summary').innerHTML=`<b>${label}</b><br>Projects: ${lastRows.length} &nbsp; | &nbsp; Frontier: ${f.length} &nbsp; | &nbsp; Frontier IDs: ${f.map(x=>x.project_id).join(', ')}`;plot(lastRows);table(f);$('download').disabled=false}
function plot(rows){const W=650,H=390,m={l:65,r:20,t:25,b:55};const xs=rows.map(r=>r.implementation_complexity),ys=rows.map(r=>r.shared_value_gain);let xmin=Math.min(...xs)*.92,xmax=Math.max(...xs)*1.05,ymax=Math.max(...ys)*1.08;const X=x=>m.l+(x-xmin)/(xmax-xmin)*(W-m.l-m.r),Y=y=>H-m.b-y/ymax*(H-m.t-m.b);let s=`<svg viewBox="0 0 ${W} ${H}"><line x1="${m.l}" y1="${H-m.b}" x2="${W-m.r}" y2="${H-m.b}" stroke="#6b7785"/><line x1="${m.l}" y1="${m.t}" x2="${m.l}" y2="${H-m.b}" stroke="#6b7785"/><text x="${W/2}" y="${H-12}" text-anchor="middle" font-size="13">Implementation Complexity (lower preferred)</text><text transform="translate(16 ${H/2}) rotate(-90)" text-anchor="middle" font-size="13">Shared Value Gain (higher preferred)</text>`;rows.forEach(r=>{let c=r.frontier?'#0b6b57':'#8aa0b4',rad=r.frontier?7:4;s+=`<circle cx="${X(r.implementation_complexity)}" cy="${Y(r.shared_value_gain)}" r="${rad}" fill="${c}" opacity="${r.frontier?1:.65}"/>`;if(r.frontier)s+=`<text x="${X(r.implementation_complexity)+8}" y="${Y(r.shared_value_gain)-8}" font-size="12" font-weight="700">${r.project_id}</text>`});s+='</svg>';$('plot').innerHTML=s}
function table(rows){$('table').innerHTML='<table><thead><tr><th>ID</th><th>Type</th><th>SVG</th><th>IC</th></tr></thead><tbody>'+rows.map(r=>`<tr class="frontier"><td>${r.project_id}</td><td>${r.event_type.replace('_',' ')}</td><td>${r.shared_value_gain.toFixed(3)}</td><td>${r.implementation_complexity.toFixed(3)}</td></tr>`).join('')+'</tbody></table>'}
$('paper').onclick=async()=>{const t=await fetch('data/paper_interventions.csv').then(r=>r.text());render(parseCSV(t),'Paper reproduction complete')};
$('file').onchange=async e=>{const t=await e.target.files[0].text();render(parseCSV(t),'CSV analysis complete')};
$('apiBtn').onclick=async()=>{try{let u=$('apiUrl').value.trim();if(!u)return;let res=await fetch(u);if(!res.ok)throw Error('HTTP '+res.status);let ct=res.headers.get('content-type')||'';let rows=ct.includes('json')?await res.json():parseCSV(await res.text());if(!Array.isArray(rows)&&rows.data)rows=rows.data;render(rows,'API analysis complete')}catch(e){$('summary').textContent='API error: '+e.message+' (public browser APIs must allow CORS).'}};
$('download').onclick=()=>{if(!lastRows.length)return;let keys=['project_id','event_type','adjusted_change_pct','annualized_kwh_saved','shared_value_gain','implementation_complexity','frontier'];let csv=keys.join(',')+'\n'+lastRows.map(r=>keys.map(k=>r[k]).join(',')).join('\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='svdf_scored.csv';a.click()};
