// Copyright 2026 Mohammad Amir Khusru Akhtar
// SPDX-License-Identifier: Apache-2.0
let lastRows=[]; const $=id=>document.getElementById(id);
function parseCSV(text){const lines=text.trim().split(/\r?\n/).filter(Boolean);const h=lines.shift().split(',').map(x=>x.trim());return lines.map(line=>{const v=line.split(',');const o={};h.forEach((k,i)=>o[k]=(v[i]??'').trim());return o})}
function rank(vals,positive=false){let arr=vals.map((v,i)=>({v:+v||0,i}));let eligible=positive?arr.filter(x=>x.v>0):arr;eligible.sort((a,b)=>a.v-b.v);let out=Array(vals.length).fill(0);if(!eligible.length)return out;let i=0;while(i<eligible.length){let j=i;while(j+1<eligible.length&&eligible[j+1].v===eligible[i].v)j++;let avg=((i+1)+(j+1))/2/eligible.length;for(let k=i;k<=j;k++)out[eligible[k].i]=avg;i=j+1}return out}
function schema(rows){let k=new Set(Object.keys(rows[0]||{}));let paper=['project_id','event_type','adjusted_change_pct','annualized_kwh_saved','capacity','gross_floor_area','pre_cv'];let general=['project_id','economic_value','environmental_value','stakeholder_reach','implementation_burden','scale','volatility'];if(paper.every(x=>k.has(x)))return 'paper';if(general.every(x=>k.has(x)))return 'general';throw Error('CSV schema not recognized. Download the template or an example below.')}
function score(rows){let mode=schema(rows),E,V,S,type,scale,vol;if(mode==='paper'){let rel=rows.map(r=>Math.max(0,-(+r.adjusted_change_pct||0)/100)),annual=rows.map(r=>Math.max(0,+r.annualized_kwh_saved||0)),area=rows.map(r=>Math.max(0,+r.gross_floor_area||0)),reach=rows.map((r,i)=>(+r.capacity||0)>0?+r.capacity:Math.sqrt(area[i]));E=rank(rel,true);V=rank(annual,true);S=rank(reach,true);type=rows.map(r=>r.event_type==='LED_Installation'?.30:r.event_type==='HVAC_Tuning'?.55:.50);scale=rank(area.map(x=>Math.log1p(x)));vol=rank(rows.map(r=>+r.pre_cv||0));}else{E=rank(rows.map(r=>r.economic_value),true);V=rank(rows.map(r=>r.environmental_value),true);S=rank(rows.map(r=>r.stakeholder_reach),true);type=rank(rows.map(r=>r.implementation_burden));scale=rank(rows.map(r=>r.scale));vol=rank(rows.map(r=>r.volatility));}
let out=rows.map((r,i)=>{let svg=(E[i]>0&&V[i]>0&&S[i]>0)?Math.cbrt(E[i]*V[i]*S[i]):0,ic=.40*type[i]+.35*scale[i]+.25*vol[i];return {...r,economic_score:E[i],environmental_score:V[i],stakeholder_score:S[i],shared_value_gain:svg,implementation_complexity:ic,schema_used:mode}});out.forEach((r,i)=>r.frontier=!out.some((q,j)=>j!==i&&q.implementation_complexity<=r.implementation_complexity&&q.shared_value_gain>=r.shared_value_gain&&(q.implementation_complexity<r.implementation_complexity||q.shared_value_gain>r.shared_value_gain)));return out}
function explain(f,mode){let best=[...f].sort((a,b)=>b.shared_value_gain-a.shared_value_gain)[0],easy=[...f].sort((a,b)=>a.implementation_complexity-b.implementation_complexity)[0];return `<h3>What the result means</h3><p>The software read <b>${lastRows.length}</b> alternatives using the <b>${mode}</b> schema. It normalized three value dimensions, combined them without allowing a zero dimension to be hidden by the others, estimated implementation complexity, and removed dominated choices.</p><p><b>${f.length}</b> alternatives survive on the Shared Value Decision Frontier. <b>${easy?.project_id||'-'}</b> is the least complex frontier option. <b>${best?.project_id||'-'}</b> has the highest shared-value gain among frontier options. Frontier membership is a screening result, not an automatic funding decision.</p>`}
function render(rows,label){try{lastRows=score(rows);let f=lastRows.filter(r=>r.frontier).sort((a,b)=>a.implementation_complexity-b.implementation_complexity),mode=lastRows[0]?.schema_used;$('summary').innerHTML=`<b>${label}</b><br>Alternatives: ${lastRows.length} &nbsp; | &nbsp; Frontier: ${f.length} &nbsp; | &nbsp; Frontier IDs: ${f.map(x=>x.project_id).join(', ')}`;plot(lastRows);table(f);$('interpret').innerHTML=explain(f,mode);$('download').disabled=false;$('results').scrollIntoView({behavior:'smooth'});}catch(e){$('summary').innerHTML='<b>Input error</b><br>'+e.message}}
function plot(rows){const W=650,H=390,m={l:65,r:20,t:25,b:55},xs=rows.map(r=>r.implementation_complexity),ys=rows.map(r=>r.shared_value_gain);let xmin=Math.min(...xs)*.92,xmax=Math.max(...xs)*1.05;if(xmax===xmin)xmax=xmin+1;let ymax=Math.max(...ys)*1.08||1,X=x=>m.l+(x-xmin)/(xmax-xmin)*(W-m.l-m.r),Y=y=>H-m.b-y/ymax*(H-m.t-m.b);let s=`<svg viewBox="0 0 ${W} ${H}"><line x1="${m.l}" y1="${H-m.b}" x2="${W-m.r}" y2="${H-m.b}" stroke="#6b7785"/><line x1="${m.l}" y1="${m.t}" x2="${m.l}" y2="${H-m.b}" stroke="#6b7785"/><text x="${W/2}" y="${H-12}" text-anchor="middle" font-size="13">Implementation Complexity (lower is preferred)</text><text transform="translate(16 ${H/2}) rotate(-90)" text-anchor="middle" font-size="13">Shared Value Gain (higher is preferred)</text>`;rows.forEach(r=>{let c=r.frontier?'#087f5b':'#9aabba',rad=r.frontier?7:4;s+=`<circle cx="${X(r.implementation_complexity)}" cy="${Y(r.shared_value_gain)}" r="${rad}" fill="${c}" opacity="${r.frontier?1:.6}"/>`;if(r.frontier)s+=`<text x="${X(r.implementation_complexity)+8}" y="${Y(r.shared_value_gain)-8}" font-size="12" font-weight="700">${r.project_id}</text>`});$('plot').innerHTML=s+'</svg>'}
function table(rows){$('table').innerHTML='<table><thead><tr><th>ID</th><th>Alternative</th><th>SVG</th><th>IC</th></tr></thead><tbody>'+rows.map(r=>`<tr class="frontier"><td>${r.project_id}</td><td>${r.project_name||String(r.event_type||'').replaceAll('_',' ')}</td><td>${r.shared_value_gain.toFixed(3)}</td><td>${r.implementation_complexity.toFixed(3)}</td></tr>`).join('')+'</tbody></table>'}
$('paper').onclick=async()=>render(parseCSV(await fetch('data/paper_interventions.csv').then(r=>r.text())),'Paper reproduction complete');$('file').onchange=async e=>{if(e.target.files[0])render(parseCSV(await e.target.files[0].text()),'CSV analysis complete')};$('apiBtn').onclick=async()=>{try{let u=$('apiUrl').value.trim();if(!u)return;let res=await fetch(u);if(!res.ok)throw Error('HTTP '+res.status);let ct=res.headers.get('content-type')||'',rows=ct.includes('json')?await res.json():parseCSV(await res.text());if(!Array.isArray(rows)&&rows.data)rows=rows.data;render(rows,'API analysis complete')}catch(e){$('summary').textContent='API error: '+e.message+' Public browser APIs must allow CORS.'}};$('download').onclick=()=>{if(!lastRows.length)return;let keys=Object.keys(lastRows[0]);let csv=keys.join(',')+'\n'+lastRows.map(r=>keys.map(k=>r[k]).join(',')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='svdf_scored.csv';a.click()};
